INSERT INTO valhalla_db.product_category_entity (id, name) VALUES (1, 'Hearthstone');
INSERT INTO valhalla_db.product_category_entity (id, name) VALUES (2, 'Hearthstone');
INSERT INTO valhalla_db.product_category_entity (id, name) VALUES (3, 'League of Legends');
INSERT INTO valhalla_db.product_category_entity (id, name) VALUES (4, 'League of Legends');
INSERT INTO valhalla_db.product_category_entity (id, name) VALUES (5, 'PUBG');
INSERT INTO valhalla_db.product_category_entity (id, name) VALUES (6, 'Dota 2');
INSERT INTO valhalla_db.product_category_entity (id, name) VALUES (7, 'PUBG');
INSERT INTO valhalla_db.product_category_entity (id, name) VALUES (8, 'CS:GO');
INSERT INTO valhalla_db.product_category_entity (id, name) VALUES (9, 'Super Smash Bros. Melee');
INSERT INTO valhalla_db.product_category_entity (id, name) VALUES (10, 'Super Smash Bros. Melee');
INSERT INTO valhalla_db.product_category_entity (id, name) VALUES (11, 'Hearthstone');
INSERT INTO valhalla_db.product_category_entity (id, name) VALUES (12, 'Super Smash Bros. Melee');
INSERT INTO valhalla_db.product_category_entity (id, name) VALUES (13, 'Super Smash Bros. Melee');
INSERT INTO valhalla_db.product_category_entity (id, name) VALUES (14, 'PUBG');
INSERT INTO valhalla_db.product_category_entity (id, name) VALUES (15, 'Overwatch');
INSERT INTO valhalla_db.product_category_entity (id, name) VALUES (16, 'Overwatch');
INSERT INTO valhalla_db.product_category_entity (id, name) VALUES (17, 'League of Legends');
INSERT INTO valhalla_db.product_category_entity (id, name) VALUES (18, 'Overwatch');
INSERT INTO valhalla_db.product_category_entity (id, name) VALUES (19, 'Super Smash Bros. Melee');
INSERT INTO valhalla_db.product_category_entity (id, name) VALUES (20, 'Dota 2');
